In [54]:
import pandas as pd

In [55]:
df = pd.read_csv("../data/auth_logs.csv")

In [75]:
df.head()

   login_attempts  failed_attempts  success  username_encoded  ip_encoded
0               1                0        1                 0           2
1               2                1        1                 4           3
2               5                5        0                 5           7
3               1                0        1                 1           4
4               7                7        0                 0           0

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   timestamp        12 non-null     object
 1   username         12 non-null     object
 2   ip_address       12 non-null     object
 3   login_attempts   12 non-null     int64
 4   failed_attempts  12 non-null     int64
 5   success          12 non-null     object
dtypes: int64(2), object(4)
memory usage: 708.0+ bytes

In [58]:
# handle missing values
df.isnull().sum()

timestamp          0
username           0
ip_address         0
login_attempts     0
failed_attempts    0
success            0
dtype: int64

In [59]:
# clean the column before mapping
df["success"] = df["success"].str.strip().str.lower()

In [60]:
# convert target label to numeric (ml model can't learn from text labels)
df["success"] = df["success"].map({"yes": 1, "no": 0})
df.head()

,timestamp,username,ip_address,login_attempts,failed_attempts,success
0,2025-01-01 09:01:12,admin,192.168.1.10,1,0,1
1,2025-01-01 09:05:43,john,192.168.1.15,2,1,1
2,2025-01-01 09:07:10,root,45.83.22.11,5,5,0
3,2025-01-01 09:10:01,alice,192.168.1.20,1,0,1
4,2025-01-01 09:15:33,admin,103.44.92.201,7,7,0

In [61]:
# drop timesatmp for new
df=df.drop(columns=['timestamp'])
df.head()

  username     ip_address  login_attempts  failed_attempts  success
0    admin   192.168.1.10               1                0        1
1     john   192.168.1.15               2                1        1
2     root    45.83.22.11               5                5        0
3    alice   192.168.1.20               1                0        1
4    admin  103.44.92.201               7                7        0

In [62]:
# encode usernames
%pip install scikit-learn
from sklearn.preprocessing import LabelEncoder

le_user = LabelEncoder()
df["username_encoded"] = le_user.fit_transform(df["username"])

df.head()

Requirement already satisfied: scikit-learn in c:\users\siddhantpatel\appdata\local\programs\python\python311\lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in c:\users\siddhantpatel\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (2.4.0)
Requirement already satisfied: scipy>=1.10.0 in c:\users\siddhantpatel\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.3.0 in c:\users\siddhantpatel\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\siddhantpatel\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

,username,ip_address,login_attempts,failed_attempts,success,username_encoded
0,admin,192.168.1.10,1,0,1,0
1,john,192.168.1.15,2,1,1,4
2,root,45.83.22.11,5,5,0,5
3,alice,192.168.1.20,1,0,1,1
4,admin,103.44.92.201,7,7,0,0

In [63]:
# handle ip addresses
le_ip = LabelEncoder()
df["ip_encoded"] = le_ip.fit_transform(df["ip_address"])

df.head()
le_ip = LabelEncoder()
df["ip_encoded"] = le_ip.fit_transform(df["ip_address"])

df.head()

,username,ip_address,login_attempts,failed_attempts,success,username_encoded,ip_encoded
0,admin,192.168.1.10,1,0,1,0,2
1,john,192.168.1.15,2,1,1,4,3
2,root,45.83.22.11,5,5,0,5,7
3,alice,192.168.1.20,1,0,1,1,4
4,admin,103.44.92.201,7,7,0,0,0

In [64]:
# drop original text columns
df = df.drop(columns=["username", "ip_address"])
df.head()

   login_attempts  failed_attempts  success  username_encoded  ip_encoded
0               1                0        1                 0           2
1               2                1        1                 4           3
2               5                5        0                 5           7
3               1                0        1                 1           4
4               7                7        0                 0           0

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   login_attempts    12 non-null     int64
 1   failed_attempts   12 non-null     int64
 2   success           12 non-null     int64
 3   username_encoded  12 non-null     int64
 4   ip_encoded        12 non-null     int64
dtypes: int64(5)
memory usage: 612.0 bytes

In [66]:
df["success"].unique()

array([1, 0])

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   login_attempts    12 non-null     int64
 1   failed_attempts   12 non-null     int64
 2   success           12 non-null     int64
 3   username_encoded  12 non-null     int64
 4   ip_encoded        12 non-null     int64
dtypes: int64(5)
memory usage: 612.0 bytes

In [68]:
df['success'].value_counts()

success
1    7
0    5
Name: count, dtype: int64

In [73]:
df.head()

   login_attempts  failed_attempts  success  username_encoded  ip_encoded
0               1                0        1                 0           2
1               2                1        1                 4           3
2               5                5        0                 5           7
3               1                0        1                 1           4
4               7                7        0                 0           0

#### training phase

In [70]:
# separate features and label
X = df.drop(columns=["success"])
y = df["success"]

In [ ]:
X.shape,y.shape

((12, 4), (12,))

In [ ]:
# test on unseen data
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

In [77]:
X_train.shape, X_test.shape

((8, 4), (4, 4))

In [79]:
# train logistic regression model(first ml model trained)
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [80]:
y_pred = model.predict(X_test)
y_pred

array([0, 1, 1, 0])

In [81]:
# evaluate model 
from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred)

1.0

In [82]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred)

array([[2, 0],
       [0, 2]])

In [83]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      1.00      1.00         2

    accuracy                           1.00         4
   macro avg       1.00      1.00      1.00         4
weighted avg       1.00      1.00      1.00         4